C
C     FFTE: A FAST FOURIER TRANSFORM PACKAGE
C
C     (C) COPYRIGHT SOFTWARE, 2000-2004, ALL RIGHTS RESERVED
C                BY
C         DAISUKE TAKAHASHI
C         GRADUATE SCHOOL OF SYSTEMS AND INFORMATION ENGINEERING
C         UNIVERSITY OF TSUKUBA
C         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
C         E-MAIL: daisuke@cs.tsukuba.ac.jp
C
C
C     GLOBAL TRANSPOSE ROUTINE
C
C     FORTRAN77 + MPI SOURCE PROGRAM
C
C     WRITTEN BY DAISUKE TAKAHASHI
C
      SUBROUTINE PZTRANS(A,B,NN,ICOMM,NPU)
      IMPLICIT REAL*8 (A-H,O-Z)
      INCLUDE 'mpif.h'
      COMPLEX*16 A(*),B(*)
      INTEGER*8 NN
C
      NN2=NN/NPU
      IF (NPU .EQ. 1) THEN
        DO 10 I=1,NN2
          B(I)=A(I)
   10   CONTINUE
      ELSE
        CALL MPI_ALLTOALL(A,NN2,MPI_DOUBLE_COMPLEX,
     1                    B,NN2,MPI_DOUBLE_COMPLEX,
     2                    ICOMM,IERR)
      END IF
      RETURN
      END
